#!/usr/bin/with-contenv bash

perl -pi -e 's#^.*access_log.*#access_log /dev/stdout;#' /etc/nginx/nginx.conf
perl -pi -e 's#^.*error_log.*#error_log /dev/stdout;#' /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
